### ISSUE TITLE
Update Heroku Stack

### ISSUE THREAD

**Issue by rubillionaire** [risd/risd-graduate-study-sync#4]
Heroku is deprecating the `heroku-16` stack that this application currently uses on May 1st, 2021. In order to continue making changes to this repository, the stack must be upgraded following the [upgrade guide][heroku-stack-upgrade-guide]. Follow the directions there and once the app stack is upgraded, this issue can be considered resolved.

[heroku-stack-upgrade-guide]:https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by room421** [comment]
@rubillionaire @cmiller02 is this on the list for this week?

**Comment by rubillionaire** [comment]
@room421 i am working on this now! will post with updates when its ready, should be able to deploy changes today and verify service continuity toady & tomorrow.

**Comment by rubillionaire** [comment]
this app on heroku has been upgraded to `heroku-20`, the latest app stack.

this required updating our version of python to one that is supported by `heroku-20`, `python-3.6.13`. to verify that this repository still functions under the new python version i used `pyenv` & a `.python-version` file to define this new version. then verified that the application still ran. with that local development environment in place, i updated the `runtime.txt` file to match our local development version of python. `runtime.txt` is what heroku uses to determine what version of python to use. i was able to deploy successfully and verify that our python coordination application is running and will continue executing our `sync-events` script that is used to pull events from localist into the https://graduatestudy.risd.edu/ CMS

`heroku-20` is supported through April 2025.

**Comment by cmiller02** [comment]
Much appreciated Ruben!

Carrie J. Miller
Digital Experience Producer
RISD MEDIA GROUP
Rhode Island School of Design
***@***.*** (401) 454-6346

**Comment by room421** [comment]
@rubillionaire I had to log into Heroku for a billing thing and I saw this. Is edu-data-sync still in use?
![Screen Shot 2021-05-12 at 9 43 54 AM](https://user-images.githubusercontent.com/4335334/117985513-c454ce80-b306-11eb-85d6-9b5a0fce16bb.png)

**Comment by rubillionaire** [comment]
@room421 looks like it still was. i went in and removed all of its compute resources, so it is no longer running.

**Comment by room421** [comment]
Was edu-data-sync related to the people feeds? Does this mean that https://from-oit.risd.systems/colleaguedata/employees/ will stop updating?

**Comment by rubillionaire** [comment]
@room421 yeah edu-data-sync was responsible for pulling XML dumps from AWS S3, published by ITS, and syncing them with the edu.risd.systems/cms firebase database. that includes XML of both courses & people.

the from-oit.risd.systems site pulls the raw XML files directly from AWS S3, so the edu-data-sync being turned off won't stop that site from working. it will just stop imports of courses, people & events from coming into edu.risd.systems/cms

**Comment by room421** [comment]
@rubillionaire Best of both worlds then! We're actually still looking at https://from-oit.risd.systems/colleaguedata/employees/ as a reference of what's in the feed on a given day. It's better organized than looking at an xml file directly.

**Comment by room421** [comment]
@rubillionaire This came in today from Heroku:

Dear Heroku Customer,

You're receiving this email because you own apps that may have non-supported DNS configurations. This email details steps for ensuring that your apps continue to work on the Heroku Platform.

In April 2021, Heroku began upgrading the infrastructure that powers the Heroku Common Runtime. The upgrade will result in improved dyno performance, regional reliability, and uptime.

The upgrade process is designed to be seamless and to not require user involvement. However, apps with unusual DNS configurations or with unusual clients accessing the app may see errors when moved to the new infrastructure. **Our analysis shows that some of your apps may need DNS tweaks in order to be migrated without error. To be certain that your application will function post-migration, please ensure that your DNS setup corresponds to the supported configurations by July 31, 2021.**

risd-systems-form-processing

When an app is migrated to the new infrastructure, its default appname.herokuapp.com, DNS records, and any haiku.herokudns.com custom domain records are modified to point to the IP addresses of the new routing infrastructure. For a period of 24-48 hours, the app is accessible via both the new and old routing infrastructure. When the migration completes, the app will no longer be accessible via the old routing infrastructure and all traffic must flow via the new infrastructure. Requests for an app sent to the old infrastructure will result in error code: H31 Misdirected Request.

**Checking App DNS**

To get correct and future-proof DNS targets for custom domains associated with your Heroku apps, you can run heroku domains and compare the DNS target in the output to the CNAME target that you've configured with your DNS provider.  If the DNS targets don't match, you need to update your DNS configuration to point to the DNS targets provided by Heroku.

If you have any SSL Endpoints associated to your app, you can verify the DNS by following this step from the SSL Endpoint setup documentation. Please note that the SSL Endpoint add-on is deprecated and will be removed starting July 31, 2021. All existing and new Heroku applications should use Heroku SSL, which includes Automated Certificate Management (ACM).

More details are available in the Custom Domain Dev Center article.

Sincerely,

The Heroku Team

**Comment by rubillionaire** [comment]
@room421 i added this to my queue. after rs-retirement & an issue that must be addressed by july 1st. will circle back and let you know what i find.

**Comment by rubillionaire** [comment]
made updates to the risd-webhook-form-processing app, adding tests to ensure that the updating the heroku stack won't cause any issues. gonna look into the dependabot alerts for this repo next week while i am actively working on this.

**Comment by cmiller02** [comment]
Thanks @rubillionaire !

**Comment by rubillionaire** [comment]
in accessing the dependabot alerts for the repo i found that in order to update our dependencies per the security alerts, that we would also have to update the version of node.js that is used to run the code. the reason being that the updated dependencies that we rely on were all coded against a newer version of node.js that is not backward compatible with the version we currently use.

this kind of upgrade requires more complete testing than just of those modules that are being updated, the whole code base is susceptible to errors of different kinds because the underlying execution engine is changing. i have a good start on complete test coverage, and will pick up on this effort next week.

this is likely going to be a consistent story for all code repositories that have have security alerts attached to them. we are currently on node.js v6 across the risd webhook ecosystem. v6 is deprecated and is no longer receiving updates, for security bugs or language features. risd-webhook-form-processing will be upgraded to v16, the latest stable version of node.js available. the rest of the ecosystem will need to follow in order to maintain security and the ability to continue leaning on other open source code that is written against newer versions of node.js.

the next task in my queue after this is to archive old repositories that don't need this attention because they are no longer in use, and then to queue up changes that need to be made in order to make security updates.

will follow up in this particular issue about my current effort, and will update the various other tickets in my queue as i make progress on them.

**Comment by rubillionaire** [comment]
okay all tests have been written, the code base has been updated, and the dependencies are all now on their latest versions. all dependabot alerts for the repo are now gone. https://github.com/risd/risd-webhook-form-processing/security/dependabot

i will look to do the same with the remaining active repositories.

**Comment by cmiller02** [comment]
Thanks so much, Ruben!

Carrie J. Miller
Digital Experience Producer
RISD MEDIA GROUP
Rhode Island School of Design
***@***.*** (401) 454-6346
